# fly.toml app configuration file generated for zara-kids-back on 2026-08-14T08:26:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zara-kids-back'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  DATA_DIR = '/data'

[[mounts]]
  source = 'zara_kids_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
