# Generated by Django 6.1 on 2026-08-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='Штрих-код')),
                ('category', models.CharField(choices=[('Куртки', 'Куртки'), ('Трикотаж', 'Трикотаж'), ('Брюки', 'Брюки'), ('Обувь', 'Обувь')], max_length=32, verbose_name='Категория')),
                ('cost_price', models.PositiveIntegerField(default=0, verbose_name='Закупочная цена')),
                ('retail_price', models.PositiveIntegerField(default=0, verbose_name='Цена продажи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазин',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('refund', 'Возврат')], max_length=16, verbose_name='Тип')),
                ('cashier_name', models.CharField(max_length=120, verbose_name='Кассир')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('total_cost', models.PositiveIntegerField(default=0, verbose_name='Себестоимость')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('qr', 'QR-код')], max_length=16, verbose_name='Способ оплаты')),
                ('authorized_by', models.CharField(blank=True, max_length=120, verbose_name='Авторизовал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('related_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='core.transaction')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='Название товара')),
                ('size', models.CharField(max_length=80, verbose_name='Размер')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('cost', models.PositiveIntegerField(verbose_name='Себестоимость')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Товар')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.transaction', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Позиция операции',
                'verbose_name_plural': 'Позиции операций',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=80, verbose_name='Размер')),
                ('stock', models.IntegerField(default=0, verbose_name='Остаток')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Размер и остаток',
                'verbose_name_plural': 'Размеры и остатки',
                'ordering': ['id'],
                'unique_together': {('product', 'size')},
            },
        ),
    ]
