# Generated by Django 6.1 on 2026-08-14 09:45

from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    for index, name in enumerate(['Куртки', 'Трикотаж', 'Брюки', 'Обувь'], start=1):
        Category.objects.update_or_create(
            name=name,
            defaults={'sort_order': index * 10, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=32, verbose_name='Категория'),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
